name: push
on:
  push:
    branches:
      - "*"
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - run: go build .
      # once we have tests...
      # - run: go test ./...
